// 班课出勤 → PDF（发给甲方）。jspdf 动态导入，避免拖大主包。
import type { DB } from './types'
import { classById, classPeriodGrid } from './selectors'
import { fmtDate, fmtDateShort } from './format'

export async function exportAttendancePDF(db: DB, classId: string, date: string) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const cls = classById(db, classId)
  const session = db.sessions.find((s) => s.classId === classId && s.date === date)
  const roster = db.students.filter((s) => s.classId === classId && s.status === 'active')
  const attFor = (studentId: string) =>
    db.attendances.find((a) => a.sessionId === session?.id && a.studentId === studentId)

  const present = roster.filter((s) => attFor(s.id)?.status === 'present').length
  const absent = roster.filter((s) => attFor(s.id)?.status === 'absent').length

  const doc = new jsPDF()
  const brand: [number, number, number] = [155, 107, 239]

  // 标题
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(58, 53, 80)
  doc.text('Attendance Record', 14, 18)
  doc.setFontSize(13)
  doc.setTextColor(brand[0], brand[1], brand[2])
  doc.text(cls?.name ?? '班级', 14, 26)

  // 副信息
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(120, 120, 130)
  doc.text(`Date: ${fmtDate(date)}`, 14, 33)
  doc.text(`Teacher: Ruby`, 14, 38)
  doc.text(`Expected: ${roster.length}   Present: ${present}   Absent: ${absent}`, 14, 43)

  // 表格
  autoTable(doc, {
    startY: 49,
    head: [['#', 'Student', 'Status', 'Note']],
    body: roster.map((s, i) => {
      const a = attFor(s.id)
      const st = a?.status === 'present' ? 'Present' : a?.status === 'absent' ? 'Absent' : '-'
      return [String(i + 1), s.name, st, a?.note ?? '']
    }),
    styles: { fontSize: 10, cellPadding: 2.5 },
    headStyles: { fillColor: brand, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 245, 251] },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center' },
      2: { cellWidth: 24, halign: 'center' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 2) {
        const v = String(data.cell.raw)
        if (v === 'Present') data.cell.styles.textColor = [91, 191, 122]
        else if (v === 'Absent') data.cell.styles.textColor = [233, 106, 91]
      }
    },
  })

  // 页脚
  const endY: number = (doc as any).lastAutoTable?.finalY ?? 60
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 160)
  doc.text('Signature: ____________________', 14, endY + 16)
  doc.text(`Generated by Ruby's Room  ·  ${fmtDate(date)}`, 14, endY + 24)

  doc.save(`${cls?.name ?? 'class'}_${date}.pdf`)
}

/**
 * 按月 / 周期导出某班出勤汇总（学生 × 课次日期矩阵 + 到课/缺勤/出勤率）。
 * 适合发给甲方做周期结算。横向 A4。
 */
export async function exportClassPeriodPDF(
  db: DB,
  classId: string,
  startISO: string,
  endISO: string,
  periodLabel: string,
) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const cls = classById(db, classId)
  const { students, dates, status } = classPeriodGrid(db, classId, startISO, endISO)
  const brand: [number, number, number] = [155, 107, 239]

  let totalPresent = 0
  let totalAbsent = 0
  const rows = students.map((s, i) => {
    let present = 0
    let absent = 0
    const cells = dates.map((d) => {
      const st = status[s.id]?.[d]
      if (st === 'present') {
        present += 1
        return '✓'
      }
      if (st === 'absent') {
        absent += 1
        return '✗'
      }
      return '—'
    })
    totalPresent += present
    totalAbsent += absent
    const denom = present + absent
    const rate = denom > 0 ? `${Math.round((present / denom) * 100)}%` : '—'
    return [String(i + 1), s.name, ...cells, String(present), String(absent), rate]
  })

  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' })

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(58, 53, 80)
  doc.text(`${cls?.name ?? '班级'} · Attendance`, 40, 30)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(brand[0], brand[1], brand[2])
  doc.text(`${periodLabel}  (${fmtDate(startISO)} – ${fmtDate(endISO)})`, 40, 46)
  doc.setTextColor(120, 120, 130)
  doc.text(
    `Teacher: Ruby   Sessions: ${dates.length}   Present: ${totalPresent}   Absent: ${totalAbsent}`,
    40,
    60,
  )

  const head = ['#', 'Student', ...dates.map((d) => fmtDateShort(d)), '到课', '缺勤', '率']
  autoTable(doc, {
    startY: 70,
    head: [head],
    body: rows.length ? rows : [['—', '（无学生）', ...dates.map(() => '')]],
    styles: { fontSize: dates.length > 8 ? 7 : 8, cellPadding: 2, overflow: 'linebreak' },
    headStyles: { fillColor: brand, textColor: 255, fontStyle: 'bold', halign: 'center' },
    columnStyles: { 0: { cellWidth: 20, halign: 'center' } },
    alternateRowStyles: { fillColor: [248, 245, 251] },
    didParseCell: (data) => {
      // 日期列居中
      if (data.section === 'body' && data.column.index >= 2 && data.column.index < 2 + dates.length) {
        data.cell.styles.halign = 'center'
        const v = String(data.cell.raw)
        if (v === '✓') data.cell.styles.textColor = [91, 191, 122]
        else if (v === '✗') data.cell.styles.textColor = [233, 106, 91]
      }
      // 汇总列
      if (data.section === 'body' && data.column.index >= 2 + dates.length) {
        data.cell.styles.halign = 'center'
        data.cell.styles.fontStyle = 'bold'
      }
    },
  })

  const endY: number = (doc as any).lastAutoTable?.finalY ?? 80
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 160)
  doc.text('Signature: ____________________', 40, endY + 22)
  doc.text(`Generated by Ruby's Room  ·  ${periodLabel}`, 40, endY + 36)

  doc.save(`${cls?.name ?? 'class'}_${startISO}_${endISO}.pdf`)
}

/**
 * 多个班课按月/区间合并导出（机构维度）：首页汇总表 + 每个班一页明细矩阵。
 * 适合把同一机构的几个班一起结算给甲方。
 */
export async function exportClassesPeriodPDF(
  db: DB,
  classIds: string[],
  startISO: string,
  endISO: string,
  label: string,
) {
  if (classIds.length === 0) return
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const brand: [number, number, number] = [155, 107, 239]

  const data = classIds.map((id) => {
    const cls = classById(db, id)
    const { students, dates, status } = classPeriodGrid(db, id, startISO, endISO)
    let present = 0
    let absent = 0
    students.forEach((s) =>
      dates.forEach((d) => {
        const st = status[s.id]?.[d]
        if (st === 'present') present += 1
        if (st === 'absent') absent += 1
      }),
    )
    return { cls, students, dates, status, present, absent }
  })

  const totalSessions = data.reduce((a, x) => a + x.dates.length, 0)
  const totalPresent = data.reduce((a, x) => a + x.present, 0)
  const totalAbsent = data.reduce((a, x) => a + x.absent, 0)
  const rate = (p: number, n: number) => (p + n > 0 ? `${Math.round((p / (p + n)) * 100)}%` : '—')

  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' })

  // 汇总页
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(58, 53, 80)
  doc.text('Attendance Summary', 40, 30)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(brand[0], brand[1], brand[2])
  doc.text(`${label}  (${fmtDate(startISO)} – ${fmtDate(endISO)})`, 40, 46)
  doc.setTextColor(120, 120, 130)
  doc.text(
    `Teacher: Ruby   Classes: ${classIds.length}   Sessions: ${totalSessions}   Present: ${totalPresent}   Absent: ${totalAbsent}`,
    40,
    60,
  )

  autoTable(doc, {
    startY: 72,
    head: [['班级', '课次', '到课人次', '缺勤人次', '出勤率']],
    body: data.map((x) => [
      x.cls?.name ?? '—',
      String(x.dates.length),
      String(x.present),
      String(x.absent),
      rate(x.present, x.absent),
    ]),
    foot: [['合计', String(totalSessions), String(totalPresent), String(totalAbsent), rate(totalPresent, totalAbsent)]],
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: brand, textColor: 255, fontStyle: 'bold' },
    footStyles: { fillColor: [243, 239, 255], textColor: 58, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 245, 251] },
    columnStyles: { 1: { halign: 'center' }, 2: { halign: 'center' }, 3: { halign: 'center' }, 4: { halign: 'center' } },
  })

  const endY: number = (doc as any).lastAutoTable?.finalY ?? 120
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 160)
  doc.text('Signature: ____________________', 40, endY + 24)
  doc.text(`Generated by Ruby's Room  ·  ${label}`, 40, endY + 38)

  // 每个班一页明细矩阵
  for (const x of data) {
    doc.addPage()
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(58, 53, 80)
    doc.text(`${x.cls?.name ?? '班级'}  ·  ${label}`, 40, 30)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(120, 120, 130)
    doc.text(`Sessions: ${x.dates.length}   Present: ${x.present}   Absent: ${x.absent}`, 40, 44)

    const head = ['#', 'Student', ...x.dates.map((d) => fmtDateShort(d)), '到课', '缺勤']
    const body =
      x.students.length === 0
        ? [['—', '（无学生）']]
        : x.students.map((s, i) => {
            let p = 0
            let a = 0
            const cells = x.dates.map((d) => {
              const st = x.status[s.id]?.[d]
              if (st === 'present') {
                p += 1
                return '✓'
              }
              if (st === 'absent') {
                a += 1
                return '✗'
              }
              return '—'
            })
            return [String(i + 1), s.name, ...cells, String(p), String(a)]
          })
    autoTable(doc, {
      startY: 54,
      head: [head],
      body,
      styles: { fontSize: x.dates.length > 8 ? 7 : 8, cellPadding: 2 },
      headStyles: { fillColor: brand, textColor: 255, fontStyle: 'bold', halign: 'center' },
      alternateRowStyles: { fillColor: [248, 245, 251] },
      columnStyles: { 0: { cellWidth: 20, halign: 'center' } },
      didParseCell: (ctx) => {
        if (ctx.section === 'body' && ctx.column.index >= 2 && ctx.column.index < 2 + x.dates.length) {
          ctx.cell.styles.halign = 'center'
          const v = String(ctx.cell.raw)
          if (v === '✓') ctx.cell.styles.textColor = [91, 191, 122]
          else if (v === '✗') ctx.cell.styles.textColor = [233, 106, 91]
        }
      },
    })
  }

  doc.save(`attendance_${startISO}_${endISO}.pdf`)
}


