// 班课某次课出勤名单 → PDF（发给甲方）。jspdf 动态导入，避免拖大主包。
import type { DB } from './types'
import { classById } from './selectors'
import { fmtDate } from './format'

export async function exportAttendancePDF(db: DB, classId: string, date: string) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  const cls = classById(db, classId)
  const session = db.sessions.find((s) => s.classId === classId && s.date === date)
  const roster = db.students.filter((s) => s.classId === classId && s.status === 'active')
  const attFor = (studentId: string) =>
    db.attendances.find((a) => a.sessionId === session?.id && a.studentId === studentId)

  const present = roster.filter((s) => attFor(s.id)?.status === 'present').length
  const absent = roster.filter((s) => attFor(s.id)?.status === 'absent').length

  const doc = new jsPDF()
  const brand: [number, number, number] = [155, 107, 239]

  // 标题
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.setTextColor(58, 53, 80)
  doc.text('Attendance Record', 14, 18)
  doc.setFontSize(13)
  doc.setTextColor(brand[0], brand[1], brand[2])
  doc.text(cls?.name ?? '班级', 14, 26)

  // 副信息
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(120, 120, 130)
  doc.text(`Date: ${fmtDate(date)}`, 14, 33)
  doc.text(`Teacher: Ruby`, 14, 38)
  doc.text(`Expected: ${roster.length}   Present: ${present}   Absent: ${absent}`, 14, 43)

  // 表格
  autoTable(doc, {
    startY: 49,
    head: [['#', 'Student', 'Status', 'Note']],
    body: roster.map((s, i) => {
      const a = attFor(s.id)
      const st = a?.status === 'present' ? 'Present' : a?.status === 'absent' ? 'Absent' : '-'
      return [String(i + 1), s.name, st, a?.note ?? '']
    }),
    styles: { fontSize: 10, cellPadding: 2.5 },
    headStyles: { fillColor: brand, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 245, 251] },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center' },
      2: { cellWidth: 24, halign: 'center' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 2) {
        const v = String(data.cell.raw)
        if (v === 'Present') data.cell.styles.textColor = [91, 191, 122]
        else if (v === 'Absent') data.cell.styles.textColor = [233, 106, 91]
      }
    },
  })

  // 页脚
  const endY: number = (doc as any).lastAutoTable?.finalY ?? 60
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 160)
  doc.text('Signature: ____________________', 14, endY + 16)
  doc.text(`Generated by Ruby's Room  ·  ${fmtDate(date)}`, 14, endY + 24)

  doc.save(`${cls?.name ?? 'class'}_${date}.pdf`)
}
